### ISSUE TITLE
Storing hash and comparing later?

### ISSUE THREAD

**Issue by GerritKuilder** [JasterV/imgphash#3]
Hi,

so far I had good results with this library but I am comparing a lot of images, very time consuming.

I wanted to store the hash of the image in a database, which would be more efficient.

The problem is that I can't seem to get the compare to work.
- stored the hash from: const thisImageResult = await HashImage.fromUrl(inImage.image);
- stored the hash as : const thisHash = await thisImageResult.phash()
- so either in mongodb store the image.hash=ThisImageResult or image.hash=thisHash

but when I use the compare function const similarity = await origHash.compare(compareHash); results in TypeError: origHash.compare is not a function'

Any ideas and/or suggestions?

Kind Regards,

Gerrit Kuilder

**Comment by JasterV** [comment]
Hi @GerritKuilder !! I wasn't expecting someone to use this in a project, this excites me!
I built this a while ago, I will review again the code and come back to you :)

**Comment by JasterV** [comment]
Ok so, how are you storing the hash in the database?
The thing is that the phash() function actually returns a class that contains the actual has value, so you should store this value in the database.
When you fetch it from the database you should first create `Phash` passing the hash as a parameter, then use the compare function

**Comment by GerritKuilder** [comment]
Tried it:

```
const image1Id = "6439657a4550977c2c37d8d8";
  const image2Id = "643965874550977c2c37e8e9";
  const image1 = await image.findById(image1Id);
  const image2 = await image.findById(image2Id);
  const image1URL = image1.image;
  console.log(image1URL);
  const image2URL = image2.image;
  console.log(image2URL);
  const image1H = await HashImage.fromUrl(image1URL);
  const image2H = await HashImage.fromUrl(image2URL);

  const hash1 = await image1H.phash(); // PHash instance
  image1.hash=hash1
  savedimage1= await image1.save()
  console.log(hash1.hash)
  const phash1=hash1.hash
  //direct compare
  const hash2 = await image2H.phash();
  image2.hash=hash2
  savedimage2= await image2.save()

  console.log(hash2);
  console.log(hash2.hash)
  const phash2=hash2.hash
  const similarity = hash1.compare(hash2);
  console.log(similarity);
  // data base values
  console.log(image1.hash)
  console.log(image2.hash)
  const similarity2 = image1.hash.compare(image2.hash);
  console.log(similarity2);
```

**Comment by GerritKuilder** [comment]
oops, somehow using only the db values don't work.
```
Orig phash:
PHash {
  hash: '0011011100111000001111000011110011111100100010000000100110011111'
}

get stored as
{
  hash: '0011011100111000001111000011110011111100100010000000100110011111'
}
```

And results in the 
phash1.compare is not a function

Back to the drawing board

**Comment by GerritKuilder** [comment]
Missed yur remark about the Phash:
  const phash11=new PHash(image1.hash.hash)
  const phash12=new PHash(image2.hash.hash)
  const similarity2 = phash11.compare(phash12);
  console.log(similarity2);

Works now

**Comment by JasterV** [comment]
Maybe I should make the `hash` property more explicit and add an example on how to get the internal hash binary sequence

Glad that it worked finally! 🚀
